name: Update Latest Substack Article

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch latest Substack post
        id: substack
        run: |
          RSS_URL="https://substack.com/feed/@peterlimg"
          ARTICLE=$(curl -s "$RSS_URL" | grep -oPm1 "(?<=<item>)[\s\S]*?(?=</item>)")
          TITLE=$(echo "$ARTICLE" | grep -oPm1 "(?<=<title>)[^<]+")
          LINK=$(echo "$ARTICLE" | grep -oPm1 "(?<=<link>)[^<]+")
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "link=$LINK" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          START="<!-- SUBSTACK:START -->"
          END="<!-- SUBSTACK:END -->"
          NEW="- [${{ steps.substack.outputs.title }}](${{ steps.substack.outputs.link }})"

          awk -v start="$START" -v end="$END" -v new="$NEW" '
            BEGIN {found=0}
            {
              if(index($0, start)) {found=1; print; print new; next}
              if(index($0, end)) {found=0}
              if(!found) print
            }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update latest Substack article in README"
          file_pattern: README.md