name: Update Latest Substack Articles

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch latest 5 Substack posts
        run: |
          RSS_URL="https://peterlimg.substack.com/feed"
          
          # Use a more robust approach with xmllint for XML cleanup
          curl -s -A "Mozilla/5.0 (compatible; RSS Reader)" "$RSS_URL" | \
          python3 -c "
          import sys
          import re
          from datetime import datetime
          
          # Read raw RSS content
          content = sys.stdin.read()
          
          # Extract items using regex (more reliable than XML parsing for malformed feeds)
          item_pattern = r'<item>(.*?)</item>'
          items = re.findall(item_pattern, content, re.DOTALL)[:5]
          
          with open('articles.txt', 'w') as f:
              for item in items:
                  # Extract title
                  title_match = re.search(r'<title><!\[CDATA\[(.*?)\]\]></title>', item)
                  if not title_match:
                      title_match = re.search(r'<title>(.*?)</title>', item)
                  
                  # Extract link
                  link_match = re.search(r'<link>(.*?)</link>', item)
                  
                  # Extract pubDate
                  pubdate_match = re.search(r'<pubDate>(.*?)</pubDate>', item)
                  
                  if title_match and link_match:
                      title = title_match.group(1).strip()
                      link = link_match.group(1).strip()
                      pubdate = pubdate_match.group(1).strip() if pubdate_match else ''
                      
                      # Format date
                      try:
                          # Remove timezone info for parsing
                          date_str = re.sub(r' [A-Z]{3}$', '', pubdate)
                          date_obj = datetime.strptime(date_str, '%a, %d %b %Y %H:%M:%S')
                          formatted_date = date_obj.strftime('%B %d, %Y')
                      except:
                          formatted_date = pubdate
                      
                      f.write(f'- [{title}]({link}) - *{formatted_date}*\n')
          "

      - name: Update README
        run: |
          START="<!-- SUBSTACK:START -->"
          END="<!-- SUBSTACK:END -->"
          
          # Create temporary file with new content
          awk -v start="$START" -v end="$END" '
            BEGIN {found=0}
            {
              if(index($0, start)) {
                found=1
                print
                next
              }
              if(index($0, end)) {
                found=0
                print
                next
              }
              if(!found) print
            }
          ' README.md > README.tmp
          
          # Insert the articles between the markers
          sed -i "/<!-- SUBSTACK:START -->/r articles.txt" README.tmp
          
          mv README.tmp README.md

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update latest Substack articles in README"
          file_pattern: README.md